name: EchoContainer - Master
on:
  push:
    branches:
      - "master"

jobs:
  building-deployment-master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1

      - name: Cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASS }}
          # registry: pelabuhan.alterra.dev

      - name: EchoContainer - Build and Push Docker Images App
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: captainaldi/golang-echo-container:v-0.0.2
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      
  deploy_to_rara:
    runs-on: ubuntu-latest
    steps:
    - name: Setup GCP / Kubectl
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        version: "290.0.1"
    - name: Setup Kubeconfig
      run: |
        cat >> ./kubeconfig <<END 
        ${{ secrets.KUBECONFIG_RARA }}
        END
    - name: Deploy
      run: |
        kubectl --kubeconfig ./kubeconfig -n renaldi set image deployment/gocheck gocheck=captainaldi/golang-echo-container:v-0.0.2 --record